Initial Introduction
MrLongbottom/P10-Article pull request #1
Opened 2021-03-09 08:05 UTC by slayeren

2021-03-09 08:12 UTC, slayeren commented on sections/introduction.tex
> +	\item \textit{Including meta-data within the \gls{lda} model, does that impact the resulting topics?}
```suggestion
	\item \textit{Including meta-data within the \gls{lda} model, how does that impact the resulting topics?}
```

2021-03-09 08:12 UTC, MrLongbottom commented on sections/introduction.tex
> +	\item \textit{Including meta-data within the \gls{lda} model, does that impact the resulting topics?}
```suggestion
	\item \textit{How does Including meta-data within the \gls{lda} model impact the resulting topics?}
```

2021-03-09 08:36 UTC, MrLongbottom requested changes

2021-03-09 08:36 UTC, MrLongbottom commented on sections/introduction.tex
> +Datasets are sometimes not used to their full potential, regarding the amount of information available within some datasets.
```suggestion
Datasets not always used to their full potential, as many projects only make use of some of the full data available.
```

2021-03-09 08:36 UTC, MrLongbottom commented on sections/introduction.tex
> +These meta-data fields within a data entry can be used for many purposes eg. to predict new samples within a certain scenario.
tror jeg syntes bedre om at starte med at beskrive topic modeling og så snakke om datasets specifict indefor topic modelling. Fordi som det står lige nu snakker vi om datasets generelt hvilket jeg syntes er meget bredt.

2021-03-09 08:36 UTC, MrLongbottom commented on sections/introduction.tex
> +Datasets consist of entries where each entry contains a certain amount of meta-data fields which describes the data.
what is data and what is meta-data?
text i topic modeling er det data eller meta-data?

2021-03-09 08:36 UTC, MrLongbottom commented on sections/introduction.tex
> +There exist many feature engineering method, which capture different aspects of a dataset, and these might aid in solving a specific task.
```suggestion
There exist many feature engineering methods, which captures different aspects of a dataset, and these might aid in solving a specific task.
```

2021-03-09 08:36 UTC, MrLongbottom commented on sections/introduction.tex
> +Meta-data is describes field within a data entry which and is usually used with supervised learning as labels for the algorithm used.
```suggestion
Meta-data describes a field within a data entry which is usually used with supervised learning as labels for the algorithm used.
```
Jeg er ikke sikker på hvad dette skal betyde, men prøvede at rette.
Don't like this sentence :/

2021-03-09 08:36 UTC, MrLongbottom commented on sections/introduction.tex
> +Within the field of topic modelling, \Gls{lda} proven successful in finding underlying topics within a corpus of text documents.
```suggestion
Within the field of topic modelling, \Gls{lda} has proven successful in finding underlying topics within a corpus of text documents.
```

2021-03-09 08:36 UTC, MrLongbottom commented on sections/introduction.tex
> +These topics are based on the document that resides in the corpus and words within these documents, but other extensions of \gls{lda} have included various other information such as authors, into the
```suggestion
These topics are constructed based on the documents in the corpus and words within these documents. However, other extensions of \gls{lda} have included various other information, such as authors, into these models to generate better topics.
```

2021-03-09 08:36 UTC, MrLongbottom commented on sections/introduction.tex
> +Nordjyske is a Danish news agency who maintain multiple newspapers throughout north Jutland, a region in Denmark.
Mangler lidt en sætning hvor vi siger at vi har tænkt os at arbejde med et specifikt dataset i dette paper.
```suggestion
In this paper, we will be taking a closer look at a specific dataset from Nordjyske and include various metadata within our topic models, to see if they can improve the quality of the topics or the efficiency of the model.
Nordjyske is a Danish news agency who maintain multiple newspapers throughout north Jutland, a region in Denmark.
```

2021-03-09 08:36 UTC, MrLongbottom commented on sections/introduction.tex
> +One of the metadata fields is the Category field, which both describes where the article is supposed to be located(within a newspaper) and also which subject the article is about.
```suggestion
One of the metadata fields is the Category field, which both describes where the article is supposed to be located (within a newspaper) and also which subject the article is about.
```
Måske vi burde beskrive alle tre metadata fields?

2021-03-09 08:36 UTC, MrLongbottom commented on sections/introduction.tex
> +These meta-data are very interesting in that they detail the data in certain ways which might be useful in some way.
intetsigende sætning. slutningen med 'in certain ways which might be useful in some way' er for vag

2021-03-18 11:31 UTC, Starrock45 reviewed
Jeg har rettet og lagt todos ind. Jeg kigger måske på et senere tidspunkt igen og skriver mere til.

2021-03-22 14:49 UTC, Starrock45 commented on sections/introduction.tex
> +
```suggestion

\todo[inline]{contributions}
```

2021-03-23 13:14 UTC, MrLongbottom approved these changes

2021-03-23 13:17 UTC, slayeren commented on sections/introduction.tex
> +This metadata includes author information, as well as higher level categorical information, which will be described in \todo{ref}.
```suggestion
This metadata includes author information, as well as higher-level categorical information, which will be described in \todo{ref}.
```

2021-03-23 13:59 UTC, Starrock45 approved these changes

2021-03-23 14:20 UTC, merged