Added to intro, related works, and dataset sections
MrLongbottom/P10-Article pull request #12
Opened 2021-03-26 13:12 UTC by Starrock45

Struktur af artikel, sidste sætning i related works og beskrivelse af boxplot i dataset afsnittet. Har også tilføjet et par små todos mere.

2021-03-29 08:09 UTC, slayeren requested changes
very minor stuff

2021-03-29 08:09 UTC, slayeren commented on sections/Dataset.tex
> +It can be seen here that the smallest category now has 188 documents, and for all categories the median category size is 3022.
```suggestion
It can be seen here that the smallest category now has 188 documents, and for all categories, the median category size is 3022.
```

2021-03-29 08:09 UTC, slayeren commented on sections/appendix/categories.tex
> +\todo[inline]{If we filter categories: Maybe highlight in the table the categories that are filtered away}
good idea

2021-03-29 08:09 UTC, slayeren commented on sections/introduction.tex
> +In \autoref{sec:experiment}, we setup an experiment to test the performance of the different metadata topic models along with their combinations and present the results.
```suggestion
In \autoref{sec:experiment}, we set up an experiment to test the performance of the different metadata topic models along with their combinations and present the results.
```

2021-04-06 08:24 UTC, slayeren approved these changes

2021-04-07 10:56 UTC, MrLongbottom approved these changes

2021-04-07 10:57 UTC, MrLongbottom commented
kan se vi har overlappet lidt nogle steder, men det finder vi ud af når vi merger nogle PRs

2021-04-07 11:45 UTC, merged