LDA expansion
MrLongbottom/P10-Article pull request #14
Opened 2021-03-31 08:08 UTC by Starrock45

Har omskrevet/tilføjet til LDA afsnittet med udgangspunkt i det der stod før.
Har prøvet at gøre det tydeligt hvilke distributions der bruges, og dimensionen/størrelsen af disse.

2021-03-31 08:49 UTC, slayeren commented on sections/plate_notation.tex
> +\Gls{lda} uncovers this semantic structure by discovering patterns of word use in documents, and finding topics based on these~\cite{blei2009topic}.
```suggestion
\Gls{lda} uncovers this semantic structure by discovering patterns of word use in documents and finding topics based on these~\cite{blei2009topic}.
```

2021-03-31 08:57 UTC, slayeren requested changes
enkelte rettelser

2021-03-31 08:57 UTC, slayeren commented on sections/plate_notation.tex
> +\Gls{lda} uncovers this semantic structure by discovering patterns of word use in documents, and finding topics based on these~\cite{blei2009topic}.
```suggestion
\Gls{lda} uncovers this semantic structure by discovering patterns of word use in documents and finding topics based on these~\cite{blei2009topic}.
```

2021-03-31 08:57 UTC, slayeren commented on sections/plate_notation.tex
> +LDA assumes that the topics are shared across the corpus, while the document-topic distributions are unique for each document.
```suggestion
\Gls{lda} assumes that the topics are shared across the corpus, while the document-topic distributions are unique for each document.
```

2021-03-31 08:57 UTC, slayeren commented on sections/plate_notation.tex
> +After training the \gls{lda} model there are multiple possibilities for exploring the corpus using the posterior distributions of the hidden random variables.
```suggestion
After training the \gls{lda} model, there are multiple possibilities for exploring the corpus using the posterior distributions of the hidden random variables.
```

2021-03-31 08:57 UTC, slayeren commented on sections/plate_notation.tex
> +One can visualize the posterior topics of the model, e.g., by sorting by the highest probabilities of words in $\beta_k$.
```suggestion
One possibility is to visualize the posterior topics of the model, e.g., by sorting $\beta_k$ according to the highest probabilities.
```

2021-03-31 08:57 UTC, slayeren commented on sections/plate_notation.tex
> +It is also possible to visualize the documents by, e.g., sorting by the highest topic proportions $\theta_d$.
```suggestion
It is also possible to visualize the documents by, e.g., sorting by the highest topic proportions in $\theta_d$.
```

2021-04-06 08:25 UTC, slayeren approved these changes

2021-04-07 10:54 UTC, MrLongbottom approved these changes

2021-04-07 11:44 UTC, merged