Appendix/authors
MrLongbottom/P10-Article pull request #15
Opened 2021-04-06 10:45 UTC by slayeren

Jeg ved ikke lige hvad mere der kan beskrives

2021-04-08 09:40 UTC, Starrock45 requested changes
Lagde mærke til at tallene i afsnittet ikke passer helt med distribution koden kørt på det nye preprocesserede data, så jeg har lavet en todo til det.

2021-04-08 09:40 UTC, Starrock45 commented on paper.tex
> +\section{Meta data}
```suggestion
\subsection{Metadata}
```
Samme problem som tidligere med at section forsvinder under appendix.

2021-04-08 09:40 UTC, Starrock45 commented on sections/appendix/authors.tex
> +\subsubsection{Author Meta data}
```suggestion
\subsubsection{Author Metadata}
```

2021-04-08 09:40 UTC, Starrock45 commented on sections/appendix/authors.tex
> +There are a total of $227$ authors within the data set where each author on average have written $757$ from 2017 to 2019.
```suggestion
There are a total of $227$ authors within the dataset where each author on average have written $757$ articles from 2017 to 2019.
```

2021-04-08 09:40 UTC, Starrock45 commented on sections/appendix/authors.tex
> +Other interesting fact that the median is $316$ which is much lower than the average which is visible in \autoref{fig:author_histogram}.
```suggestion
An interesting fact is that the median is $316$ which is much lower than the average which is visible in \autoref{fig:author_histogram}.
This shows that while most authors have written just a few hundred articles, there is a small amount of authors that have written thousands of articles, increasing the average.
```

2021-04-08 09:40 UTC, Starrock45 commented on sections/appendix/authors.tex
> +When we look at the top two most writing authors, we get two people:
```suggestion
When we look at the top two most writing authors, we get these:
```

2021-04-08 09:40 UTC, Starrock45 commented on sections/appendix/authors.tex
> +	\caption{A histogram over the number of articles each author has written.}
```suggestion
	\caption{A histogram over the number of articles authors have written.}

```

2021-04-08 09:40 UTC, Starrock45 commented on sections/appendix/authors.tex
> +	\item Ove Nørhave
```suggestion
	\item Ove Nørhave (9893 articles)

```

2021-04-08 09:40 UTC, Starrock45 commented on sections/appendix/authors.tex
> +	\item System Administrator
```suggestion
	\item System Administrator (9038 articles)

```

2021-04-08 09:40 UTC, Starrock45 commented on paper.tex
> +\subsection{Metadata}
```suggestion
\subsection{Metadata}
\todo[inline]{Update numbers in metadata sections when preprocessing is completely finished.}
```

2021-04-08 10:45 UTC, Starrock45 reviewed
En ekstra ting der kan tilføjes.

2021-04-08 10:45 UTC, Starrock45 commented on sections/appendix/authors.tex
> +In \autoref{fig:author_histogram}, we see that the vast majority of authors have written under $2000$ articles within the three years.
Jeg fik lavet koden der genererer latex tables, bygget på distribution.py. Ville have smidt tabellen i en fil, men det kan jeg ikke gøre direkte på github.
```suggestion
In \autoref{fig:author_histogram}, we see that the vast majority of authors have written under $2000$ articles within the three years. 
All authors and the number of articles they have written can be seen in \autoref{tab:author_table}.

\begin{table*}[h]
	\centering
	\scriptsize
	\begin{tabular}{l|c|l|c|l|c|l|c}
		Author                & Number & Author                     & Number & Author                       & Number & Author                       & Number \\
		\toprule
		Ove Nørhave           &  9893  & Bent Stenbakken            &  646   & Katrine Schousboe            &  189   & Sarah Sandhøj                &   35   \\
		System Administrator  &  9038  & Lars Hofmeister            &  628   & Mathias Majlund Laursen      &  178   & Suzanne Tram                 &   34   \\
		Ole Fink Mejlgaard    &  6518  & Anne Helene Thomsen        &  606   & Anne Brik Jensen             &  177   & Sebastian Engelberth Hansen  &   33   \\
		Peter Tordrup Larsen  &  5002  & Max Melgaard               &  587   & Peder Pedersen               &  166   & Anna Østergaard Bjørn        &   29   \\
		Kim Juhl Andersen     &  4506  & Karen Marie Foldbjerg      &  580   & Carl Åge Østergaard          &  152   & Michael Sand Andersen        &   27   \\
		Jeppe Damsgaard       &  4057  & Lise Larsen                &  575   & Mette Siggaard               &  150   & HANNE Lindblad Jensen        &   27   \\
		Jørn Larsen           &  3863  & Asbjørn Hansen             &  566   & Karen Keinicke               &  150   & Mathilde Juul Back Jensen    &   25   \\
		Jørn Eriksen          &  3395  & Peter Witten               &  544   & Tune Kristensen              &  149   & Allan Bauer                  &   19   \\
		Anders Kjærgaard      &  2960  & Allan Vinding Sørensen     &  534   & Morten Brændstrup            &  146   & Linse Daugaard               &   18   \\
		Søren Beukel Bak      &  2811  & Dorrit Gap Jensen          &  530   & Emil Halkier                 &  143   & Morten Nis Klenø             &   17   \\
		Søren Olsson          &  2558  & Hans Christensen           &  500   & Britt Kristensen             &  135   & OLE SANVIG KNUDSEN           &   16   \\
		Jens Peter Svarrer    &  2480  & Lars Høj                   &  493   & KAREN Marie Foldbjerg        &  132   & Frederik Siiger              &   15   \\
		Flemming Kristensen   &  2282  & Jesper Ramsing             &  469   & Claus Smidstrup              &  128   & Kim Lesanner                 &   15   \\
		Thomas Jasper         &  2186  & Jens Hukiær                &  464   & Sarah Thun Madsen            &  127   & Pia Haugaard                 &   13   \\
		Bente Lembo           &  2128  & Svend Ole Jensen           &  447   & Jakob Kanne Bjerregaard      &  126   & MERETE HORN                  &   12   \\
		Helle Møller Larsen   &  1787  & Martin Frandsen            &  437   & Lars Teilmann                &  122   & Regitze Ørnstrup Christensen &   12   \\
		Claus Jensen          &  1739  & Tobias Brandt              &  423   & Natasha Jahanshahi           &  117   & Inge Steen Sørensen          &   11   \\
		Esben Heine Pedersen  &  1689  & Andrea Jessen Jakobsen     &  423   & Jens Ole Pedersen            &  116   & Anika Thorø Møller           &   11   \\
		Margit Sig            &  1632  & Carsten Søgaard Jensen     &  420   & Pauline Bülow                &  116   & Tim Søgaard                  &   11   \\
		Jens Fogh-Andersen    &  1614  & Morten Lind                &  413   & Christoffer Green Sørensen   &  115   & Flemming Haslund             &   10   \\
		Ole Jensen            &  1611  & Esben Agerlin Olsen        &  406   & Flemming Junker              &  103   & Henrik Nordstrøm Mortensen   &   10   \\
		David Højmark         &  1549  & Carsten Hougaard           &  406   & Niklas Grønborg              &  103   & Emil Halkær                  &   9    \\
		Niels Hansen          &  1512  & Dorit Glintborg            &  405   & Sofie Møller                 &   99   & Katrine Hjulmann Nielsen     &   9    \\
		Line Lykkegaard Skou  &  1504  & Karin Pedersen             &  397   & Michael Strandfelt           &   98   & John Jensen                  &   8    \\
		Lars Bang Bertelsen   &  1443  & Kasper Ørkild              &  393   & Anders Sønderup              &   95   & Jacob Eggert Kabel           &   8    \\
		Villy Dall            &  1408  & Marianne Isen              &  387   & Søren Kjær                   &   95   & Søren Dietrichsen            &   7    \\
		Hans Peter Kragh      &  1403  & Jakob Gammelgaard          &  385   & Lone Beck                    &   92   & Nicolai Østergaard           &   6    \\
		Claus T. Kræmmergård  &  1354  & Dorte Geertsen             &  383   & Torben O. Andersen           &   91   & Søren L. Hviid               &   6    \\
		Lars Christensen      &  1293  & Torben Duch Holm           &  364   & Mikkel Færgemann Viken       &   91   & Kathrine Lykkegaard Jeppesen &   5    \\
		Rasmus Skovbo         &  1253  & Henrik Strømgaard          &  362   & Hans Henrik Rasmussen        &   90   & Ursula Rechnagel Taylor      &   5    \\
		Anders Abildgaard     &  1229  & Lisbeth Helleskov          &  361   & Steffen Bek                  &   89   & Jens Otto Barsøe             &   4    \\
		Lasse Damsgaard       &  1209  & Niels Brauer               &  358   & Simon Kjær Jensen            &   86   & Maria Berg Badstue Pedersen  &   4    \\
		Søren Østergaard      &  1207  & Jesper Poulsen             &  348   & Michael Sand                 &   85   & Jacob Andersen               &   3    \\
		Hanne Lindblad Jensen &  1191  & Lars Termansen             &  328   & Julian Drud Sørensen         &   84   & Christian Brahe-Pedersen     &   3    \\
		Charlotte Bøje        &  1117  & Mikkel Eklund              &  328   & Tina Larsen                  &   82   & Helle-Lise Ritzau Kaptain    &   3    \\
		Morten Kyndby Holm    &  1102  & Susie Skov                 &  323   & Nils Rasmussen               &   79   & Jane Schmidt Klausen         &   3    \\
		Lars Aare Jensen      &  1084  & Birgitte Sonne             &  321   & Katrine Hjulmann             &   73   & Ebbe Fischer                 &   3    \\
		Hanne Overbye         &  1075  & Anders Andersen            &  315   & Mathias Lykke                &   72   & Stefan Buur Hansen           &   3    \\
		Lise Stenbro          &  1029  & Gunnar Onghamar            &  309   & Caspar Birk                  &   71   & Camilla Pehrson              &   2    \\
		Lone Lærke Krog       &  1005  & Carl Emil Nielsen          &  305   & Anna Bech Sørensen           &   69   & Danske Fagmedier master      &   2    \\
		Carsten Tolbøll       &  1004  & Emma Toftelund Poulsen     &  299   & Fie Dømler                   &   65   & testbruger                   &   2    \\
		Mette Møller          &  974   & Ole Sanvig Knudsen         &  287   & Poul Christoffersen          &   65   & Anders Fuglsang              &   2    \\
		Ida Smith             &  973   & Charlotte Rørth            &  276   & Søren Skov                   &   56   & Peter Kargaard               &   2    \\
		Merete Horn           &  929   & Morten Appel               &  273   & Nana Sofia Hansen            &   54   & Morten Munk Andersen         &   2    \\
		Pernille K. Damsgaard &  922   & Kristian Gull Pedersen     &  266   & Tobias Reffstrup Rasmussen   &   53   & JSLbruger Nordjyske          &   2    \\
		Lars Løcke            &  873   & Birgitte Bové              &  262   & AAArtikler parkeret          &   51   & Jan M. Jensen                &   1    \\
		Thomas Nielsen        &  841   & Helle Madsen               &  258   & Camilla Gammelgaard Johansen &   50   & Tom Andersson                &   1    \\
		Jakob Frey Ahrentzen  &  832   & Kasper Orkild Hansen       &  255   & Klaus Færch Gjerulff         &   49   &  [...]

2021-04-13 09:09 UTC, Starrock45 approved these changes

2021-04-15 07:12 UTC, MrLongbottom approved these changes

2021-04-15 10:27 UTC, merged