Preprocessing of metadata
MrLongbottom/P10-Article pull request #16
Opened 2021-04-07 10:41 UTC by MrLongbottom

2021-04-07 11:42 UTC, slayeren requested changes
nogle stavefejl og nogle sætningsændringer

2021-04-07 11:42 UTC, slayeren commented on sections/Dataset.tex
> +After filtering away authors that have written less that $14$ documents ($\tilde0.001\%$ of the total document set), 184 remain.
```suggestion
Originally there were $227$ different authors within the dataset.
After filtering away authors that have written less than $14$ documents ($\tilde0.001\%$ of the total document set), 184 remain.
```

2021-04-07 11:42 UTC, slayeren commented on sections/Dataset.tex
> +However there are also nonsensical categories such as '53. Frederik', that do not seem to describe the subject of the document.
```suggestion
However, there are also nonsensical categories such as '53. Frederik', that does not seem to describe the subject of the document.
```

2021-04-07 11:42 UTC, slayeren commented on sections/Dataset.tex
> +There are also a few other top-level taxonomies, however they are not as informative and very rarely used.
```suggestion
There are also a few other top-level taxonomies however they are not as informative and very rarely used.
```

2021-04-07 11:42 UTC, slayeren commented on sections/Dataset.tex
> +Originally there were $1135$ different taxonomies, however after removing taxonomies used by less tham $4$ documents ($\tilde 0.01\%$ of the amount of documents with taxonomies), $613$ remain.
```suggestion
Originally there were $1135$ different taxonomies however after removing taxonomies used by less than $4$ documents ($\tilde 0.01\%$ of the number of documents with taxonomies), $613$ remain.
```

2021-04-07 11:42 UTC, slayeren commented on sections/appendix/categories.tex
> +Categories with fewer than 139 documents ($0.1$ of number of documents), are removed as part of preprocessing, and replaced with a single misc category 'misc'.
```suggestion
Categories with fewer than 139 documents ($0.1$ of the number of documents) are removed as part of preprocessing and replaced with a single misc category 'misc'.
```

2021-04-07 11:42 UTC, slayeren commented on sections/appendix/categories.tex
> +This reduces the amount of categories to $34$, while only replacing 292 document's categories to 'misc'.
```suggestion
This reduces the number of categories to $34$, while only replacing 292 document categories with 'misc'.
```

2021-04-07 11:42 UTC, slayeren commented on sections/appendix/categories.tex
> +	\caption{Amount of documents with each category within the Nordjyske dataset from 2017 to 2019. Categories marked with * are removed as part of metadata preprocessing.}
```suggestion
	\caption{Amount of documents with each category within the Nordjyske dataset from 2017 to 2019. 
	Categories marked with * are removed as part of metadata preprocessing.}
```

2021-04-07 11:42 UTC, slayeren commented on sections/appendix/categories.tex
> +Unlike with Categories, the Author metadata field does not a have a natural cut off points, with a good amount of values in a specific lower range, followed by more evenly distributed numbers.
```suggestion
Unlike with Categories, the Author metadata field does not have a natural cut-off point, with a good amount of values in a specific lower range, followed by more evenly distributed numbers.
```

2021-04-07 11:42 UTC, slayeren commented on sections/appendix/categories.tex
> +Instead a vast majority of the values fall in a lower range, meaning that setting too high a cut off point, will result in removing a large portion of the data.
```suggestion
Instead, the vast majority of the values fall in a lower range, meaning that setting too high a cut-off point, will result in removing a large portion of the data.
```

2021-04-07 11:42 UTC, slayeren commented on sections/appendix/categories.tex
> +Instead we choose a lower cut off point, keeping most of the authors, except the ones that contained so few documents, that finding common topics would be inefficient.
```suggestion
We instead choose a lower cut-off point, keeping most of the authors, except the ones that contained so few documents, that finding common topics would be inefficient.
```

2021-04-07 11:42 UTC, slayeren commented on sections/appendix/categories.tex
> +Authors who have written less that $14$ documents ($0.01\%$ of the number of documents) are removed as part of preprocessing.
```suggestion
Authors, who have written less than $14$ documents, ($0.01\%$ of the number of documents) are removed as part of preprocessing.
```

2021-04-07 11:42 UTC, slayeren commented on sections/appendix/categories.tex
> +For preprocessing we remove any sub-taxonomy that is used in less that $4$ taxonomy sequences.
```suggestion
We remove any sub-taxonomy that is used in less than $4$ taxonomy sequences.
```

2021-04-08 07:54 UTC, MrLongbottom commented on sections/appendix/categories.tex
> +Authors who have written less that $14$ documents ($0.01\%$ of the number of documents) are removed as part of preprocessing.
```suggestion
Authors, who have written less than $14$ documents ($0.01\%$ of the number of documents), are removed as part of preprocessing.
```

2021-04-08 07:55 UTC, MrLongbottom commented on sections/appendix/categories.tex
> +This reduces the amount of categories to $34$, while only replacing 292 document's categories to 'misc'.
```suggestion
This reduces the number of categories to $34$, while only replacing 292 documents to have the 'misc' category.
```

2021-04-08 13:15 UTC, Starrock45 requested changes
Nogle enkelte ting. Der skal lige holdes øje når #15 og denne PR merges ind på main, da de begge skriver her i appendix.

2021-04-08 13:15 UTC, Starrock45 commented on sections/Dataset.tex
> +Originally there were $1135$ different taxonomies however after removing taxonomies used by less than $4$ documents ($\tilde 0.01\%$ of the number of documents with taxonomies), $613$ remain.
Er det rent faktisk 0.01, og ikke 0.001 af taxonomy dokument sættet der giver 4? Ved hurtig hovedregning synes jeg 0.001 giver mere mening.

2021-04-08 13:15 UTC, Starrock45 commented on sections/appendix/categories.tex
> +Categories with fewer than 139 documents ($0.1$ of the number of documents) are removed as part of preprocessing and replaced with a single misc category 'misc'.
```suggestion
Categories with fewer than 139 documents ($0.1$ of the number of documents) are removed as part of preprocessing and replaced with a single miscellaneous category 'misc'.
```

2021-04-08 13:15 UTC, Starrock45 commented on sections/appendix/categories.tex
> +	\caption{Histogram over amount of categories different number of documents, before and after preprocessing. Categories in the x-axis are grouped into 50 buckets.}
```suggestion
	\caption{Histogram over the number of categories for different number of documents, before and after preprocessing.
	Categories on the x-axis are grouped into 50 buckets.}
```

2021-04-08 13:15 UTC, Starrock45 commented on sections/appendix/categories.tex
> +	Categories marked with * are removed as part of metadata preprocessing.}
Tabellen på main er opdateret så den er sorteret. Om vi bruger fed markering, eller * må vi lige vurdere senere.

2021-04-08 13:15 UTC, Starrock45 commented on sections/appendix/categories.tex
> +	\caption{Histogram over amount authors who have written certain number of documents, before and after preprocessing. Authors in the x-axis are grouped into 50 buckets.}
```suggestion
	\caption{Histogram over amount authors who have written certain number of documents, before and after preprocessing.
	Authors on the x-axis are grouped into 50 buckets.}
```

2021-04-12 09:28 UTC, MrLongbottom commented on sections/Dataset.tex
> +Originally there were $1135$ different taxonomies however after removing taxonomies used by less than $4$ documents ($\tilde 0.01\%$ of the number of documents with taxonomies), $613$ remain.
```suggestion
Originally there were $1135$ different taxonomies however after removing taxonomies used by less than $4$ documents ($\tilde 0.001\%$ of the number of documents with taxonomies), $613$ remain.
```

2021-04-12 09:29 UTC, MrLongbottom commented on sections/appendix/categories.tex
> +	Categories marked with * are removed as part of metadata preprocessing.}
ja, vi skal nok bare beholde den på main og så markere bagefter.

2021-04-12 10:34 UTC, slayeren approved these changes

2021-04-14 07:30 UTC, Starrock45 approved these changes

2021-04-15 09:43 UTC, Starrock45 commented on sections/Dataset.tex
> +Originally there were $1135$ different taxonomies however after removing taxonomies used by less than $4$ documents ($\tilde 0.001\%$ of the number of documents with taxonomies), $613$ remain.
```suggestion
Originally there were $1135$ different taxonomies; however, after removing taxonomies used by less than $14$ documents ($\tilde 0.001\%$ of the total document set), $???$ remain.
```
Kan ikke huske det specifikke nye antal dokumenter.

2021-04-15 09:45 UTC, Starrock45 commented on sections/Dataset.tex
> +There are also a few other top-level taxonomies however they are not as informative and very rarely used.
```suggestion
There are also a few other top-level taxonomies; however, they are not as informative and very rarely used.
```

2021-04-15 10:51 UTC, merged