Added explanation to how we did grid search
MrLongbottom/P10-Article pull request #17
Opened 2021-04-07 11:05 UTC by slayeren

2021-04-08 11:56 UTC, Starrock45 requested changes

2021-04-08 11:56 UTC, Starrock45 commented on sections/Experiment.tex
>  To evaluate the \gls{lda} model, we measure the topic coherence of the model after training it on the dataset for ?? epochs.
```suggestion
To evaluate the \gls{lda} model, we measure the topic coherence of the model after training it on the dataset for 50 epochs.
```
Ser det ud til ud fra billederne på kunst kanalen.

2021-04-08 11:56 UTC, Starrock45 commented on tables/grid_search.tex
> +	\caption{Tested hyperparameter values. $K_1$ is the $K$ values used for the random gridsearch, where we tested each $K$ value with a random chosen $\alpha$ and $\eta$, while $K_2$ is the $K$ values
Noget af det her med random grid search, og at der køres to grid searches burde nok også beskrives i teksten tidligere.

2021-04-08 11:56 UTC, Starrock45 commented on tables/grid_search.tex
> +		$\eta$ & \textbf{0.1}, \textbf{0.01}, 0.001\\
Hvorfor 0.001 ikke bruges i den store grid search burde nævnes i teksten.

2021-04-08 11:56 UTC, Starrock45 commented on tables/grid_search.tex
> +	\caption{Tested hyperparameter values. $K_1$ is the $K$ values used for the random gridsearch, where we tested each $K$ value with a random chosen $\alpha$ and $\eta$, while $K_2$ is the $K$ values
```suggestion
	\caption{Tested hyperparameter values. $K_1$ is the $K$ values used for the random gridsearch, where we tested each $K$ value with a random chosen $\alpha$ and $\eta$, while $K_2$ is the $K$ values used for the grid search in conjunction with the bolded values in $\alpha$ and $\eta$.}
```

2021-04-09 09:13 UTC, Starrock45 approved these changes

2021-04-12 09:30 UTC, MrLongbottom approved these changes

2021-04-12 10:34 UTC, merged