Appendix: Weird categories
MrLongbottom/P10-Article pull request #18
Opened 2021-04-09 11:25 UTC by Starrock45

Har skrevet om '26. Frederik' og '53. Frederik' kategorierne, med observationerne som jeg havde snakket om tidligere.
Hvor den placeres i appendix skal lige fikses når de andre PR'er også merges.

2021-04-12 09:48 UTC, MrLongbottom approved these changes

2021-04-12 09:48 UTC, MrLongbottom commented on sections/appendix/categories.tex
> +We continue to use these categories in our experiment, because we might make other observations through the topic models.
```suggestion
We continue to use these categories in our experiment, for the possibility of making other observations through the topic models.
```

2021-04-12 10:42 UTC, rasmus-e-christensen requested changes
some minor changes

2021-04-12 10:42 UTC, rasmus-e-christensen commented on sections/appendix/categories.tex
> +As mentioned in \autoref{sec:dataset}, there are some nonsensical categories that are worth mentioning.
```suggestion
As mentioned in \autoref{sec:dataset}, some nonsensical categories are worth mentioning.
```

2021-04-12 10:42 UTC, rasmus-e-christensen commented on sections/appendix/categories.tex
> +The topics written can be about anything from sports to news from around the world or locally in Denmark.
```suggestion
The topics, within these categories, can be about anything from sports to news from anywhere around the world or locally in Denmark.
```
er det om kategoriene eller generelt?

2021-04-12 10:42 UTC, rasmus-e-christensen commented on sections/appendix/categories.tex
> +By looking at a random selection of documents from these categories, there can not be seen any pattern of topics.
```suggestion
By looking at a random selection of documents from these categories, there is no clear pattern to be found.
```

2021-04-12 10:42 UTC, rasmus-e-christensen commented on sections/appendix/categories.tex
> +All articles seem to be from 2019, the last year in our dataset, but spread over the whole year.
```suggestion
The articles from '26. Frederik' appear all years in our dataset, while the articles for '53. Frederik' seem to be just from 2019, the last year in our dataset, but evenly distributed over the whole year.
```
er det sådan nogenlunde ?

2021-04-12 10:42 UTC, rasmus-e-christensen commented on sections/appendix/categories.tex
> +Curiously enough, most of the documents from these categories seem to be written by Anders Kjærgaard, with only a few other authors.
```suggestion
Curiously enough, most of the documents from these categories seem to be written by Anders Kjærgaard, with only a few other interfering authors.
```

2021-04-14 09:53 UTC, slayeren approved these changes

2021-04-14 10:45 UTC, merged