Preprocessing
MrLongbottom/P10-Article pull request #19
Opened 2021-04-12 10:17 UTC by Starrock45

Beskrivelse af vores dokument preprocessering. Placeret i Dataset afsnittet, da det gav mest mening der.

2021-04-12 10:29 UTC, slayeren requested changes
har nogle enkelte sætnings ændringer

2021-04-12 10:29 UTC, slayeren commented on sections/Dataset.tex
> +Some basic preprocessing is done to the dataset, to make it more applicable for topic models.
```suggestion
We perform some basic preprocessing to make the data more applicable for topic models.
```

2021-04-12 10:29 UTC, slayeren commented on sections/Dataset.tex
> +Firstly, because this dataset includes articles from multiple cities and regions, there appear duplicates in the dataset.
```suggestion
Firstly, because the dataset includes articles from multiple cities and regions, duplicates do occur in the dataset.
```

2021-04-12 10:29 UTC, slayeren commented on sections/Dataset.tex
> +After this, we filter out words that appear in less than 10 articles and words that appear more than 10$\%$ of articles.
```suggestion
After this, we filter out words that appear in less than 10 articles and words that appear in more than 10$\%$ of articles.
```

2021-04-12 10:29 UTC, slayeren commented on sections/Dataset.tex
> +This is done both to only keep words that are used enough to find patterns in topics and to remove words that are similar to stop words.
```suggestion
This is done to keep words that are used enough to find patterns in topics and to remove words that are similar to stop words.
```

2021-04-12 10:29 UTC, slayeren commented on sections/Dataset.tex
> +Finally, after words are filtered out, the documents that end up empty are removed.
```suggestion
Finally, after the words are filtered out, the empty documents are removed.
```

2021-04-14 09:54 UTC, slayeren approved these changes

2021-04-15 07:22 UTC, MrLongbottom approved these changes

2021-04-15 09:57 UTC, merged