Applications section
MrLongbottom/P10-Article pull request #22
Opened 2021-04-13 11:12 UTC by slayeren

2021-04-14 11:31 UTC, Starrock45 requested changes
Forslag rundt omkring. Afsnittet ender mere spørgende end jeg havde forventet, men det er nok ok som en reflekterende slutning.

2021-04-14 11:31 UTC, Starrock45 commented on sections/appendix/applications.tex
> +There are a variety of different applications, which topic modeling can be used for.
```suggestion
There are a variety of different applications that topic modeling can be used for. 
```

2021-04-14 11:31 UTC, Starrock45 commented on sections/appendix/applications.tex
> +The \gls{lda} model, created by \citet{blei2003latent}, has seen many extension over the years to try an improve the generality of the model.
```suggestion
The \gls{lda} model, created by \citet{blei2003latent}, has seen many extensions over the years to try and improve the generality of the model.
```

2021-04-14 11:31 UTC, Starrock45 commented on sections/appendix/applications.tex
> +Normally \gls{lda} works by inferring hidden topic structure, which is based on two topic distribution, namely document-topic and topic-word distributions.
```suggestion
Normally \gls{lda} works by inferring hidden topic structure, which is based on two distributions, namely the document-topic and topic-word distributions.
```

2021-04-14 11:31 UTC, Starrock45 commented on sections/appendix/applications.tex
> +This idea of taking meta-information into account seems to be overlooked, even though a few papers have touched upon this area, the application possibilities for these kind of meta-information integr
```suggestion
This idea of taking meta-information into account seems to be overlooked, even though a few papers have touched upon this area, the application possibilities for these kind of meta-information integrations are endless.
```

2021-04-14 11:31 UTC, Starrock45 commented on sections/appendix/applications.tex
> +News media groups, like Nordjyske, are trying to find new ways of integrating smarter and more intelligent methods for keeping their customers and using topic modeling can be help improve their proce
```suggestion
News media groups, like Nordjyske, are trying to find new ways of integrating smarter and more intelligent methods for keeping their customers, and using topic modeling can help improve their processes in different ways.
```

2021-04-14 11:31 UTC, Starrock45 commented on sections/appendix/applications.tex
> +One case could be that they want to search better through their articles.
```suggestion
One case could be that they want better search functionality for their articles.
```

2021-04-14 11:31 UTC, Starrock45 commented on sections/appendix/applications.tex
> +This problem could be alleviated by using the topic distributions created by our LDA, to specifically target certain types of topics and group articles together with very similar topic distributions,
```suggestion
This problem could be alleviated by using the topics created by our \gls{lda} model, to specifically target certain types of topics and group articles together with very similar topic distributions, like sports articles.
```

2021-04-14 11:31 UTC, Starrock45 commented on sections/appendix/applications.tex
> +One very important problem, within news agencies, are recommendation of articles.
```suggestion
One very important problem, within news agencies, is recommendation of articles.

```

2021-04-14 11:31 UTC, Starrock45 commented on sections/appendix/applications.tex
> +Many algorithms have already been develop for solving the recommendation problem but incorporating topic within these model could improve the recommendation if scoring of the articles was possible.
```suggestion
Many algorithms have already been developed for solving the recommendation problem but incorporating topics within these models could improve the recommendation if scoring of the articles was possible.
```
Jeg kan ikke se forbindelsen mellem at bruge topics til recommendations og at scoring er nødvendigt.

2021-04-14 11:31 UTC, Starrock45 commented on sections/appendix/applications.tex
> +Then, scoring of the articles could be used in recommendation for a wide variety of different users, who might take a like to that specific article.
```suggestion
Then, scoring of the articles could be used in recommendation for a wide variety of different users, who might take a liking to that specific article.
```

2021-04-14 11:31 UTC, Starrock45 commented on sections/appendix/applications.tex
> +One of the very important points of our goal is to emphasize the importance of meta-data and how it can affect the applications of the future.
```suggestion
One important goal of ours is to emphasize the importance of metadata and how it can affect future applications.
```

2021-04-14 11:31 UTC, Starrock45 commented on sections/appendix/applications.tex
> +How can meta-information describing location specific information, like Category or Taxonomy, influence the topics created.
```suggestion
How can meta-information, such as geographic locations from the Category or Taxonomy fields, influence the topics created.
```
Prøvede at ændre på det, da jeg ikke umiddelbart tænker på category og taxonomy som `location specific`.

2021-04-14 11:31 UTC, Starrock45 commented on sections/appendix/applications.tex
> +Can the time information be used to figure out whether a certain article gets better performance on another date?
```suggestion
Can time information be used to figure out whether a certain article gets better performance on another date?
```

2021-04-15 08:40 UTC, MrLongbottom requested changes
Kan ikke så godt lide starten.
Derudover er jeg enig med dennis i at afsnittet lige nu er for spørgene.
Vi burde sige hvilke cool ting er mulige frem for at spørge 'kunne vi?'

2021-04-15 08:40 UTC, MrLongbottom commented on sections/appendix/applications.tex
> +There are a variety of different applications, which topic modeling can be used for.
```suggestion
There are a variety of different applications that topic modeling could be used for. 

```

2021-04-15 08:40 UTC, MrLongbottom commented on sections/appendix/applications.tex
> +This idea of taking meta-information into account seems to be overlooked, even though a few papers have touched upon this area, the application possibilities for these kind of meta-information integr
We begin by saying there are many different application, but then we don't talk about the applications, we talk about how lda works and what extensions have been made, etc.
Line 3-7 seems kinda out of place / not sure what they are trying to do.
We do mention application of exploring something over time, but we don't do that, so I'm not sure why we are pointing it out.

2021-04-19 07:34 UTC, Starrock45 requested changes

2021-04-19 07:34 UTC, Starrock45 commented on sections/appendix/applications.tex
> +
```suggestion
```
Den ekstra linje burde vidst ikke være kommet med

2021-04-19 07:34 UTC, Starrock45 commented on sections/appendix/applications.tex
```suggestion
```
Ny paragraf er nok heller ikke nødvendig her.

2021-04-19 07:34 UTC, Starrock45 commented on sections/appendix/applications.tex
> +How can meta-information, such as geographic locations from the Category or Taxonomy fields, influence the topics created.
```suggestion
How can meta-information, such as geographic locations from the Category or Taxonomy fields, influence the topics created?
```

2021-04-19 07:34 UTC, Starrock45 commented on sections/appendix/applications.tex
> +Then, scoring of the articles could be used in recommendation for a wide variety of different users, who might take a liking to that specific article.
Er stadig ikke sikker på hvad forbindelsen er mellem at bruge topics og at give artikler en score.
Snakker vi om scorer som brugerne giver, eller en score af hvor mange brugere der besøger en artikel? Og hvad gør topic information som kan gøre recommendationen bedre med scoring?

2021-04-20 09:10 UTC, slayeren commented on sections/appendix/applications.tex
> +Then, scoring of the articles could be used in recommendation for a wide variety of different users, who might take a liking to that specific article.
Det kunne f.eks være hvor mange der har læst artikelen. og topic information kunne så finde ud af hvilke topics læserne godt kan lide at læse om.

2021-04-20 11:21 UTC, Starrock45 commented on sections/appendix/applications.tex
> +Then, scoring of the articles could be used in recommendation for a wide variety of different users, who might take a liking to that specific article.
```suggestion
Many algorithms have already been developed for solving the recommendation problem but incorporating topics within these models could improve the recommendation if scoring of the articles was possible.
Then, scoring of the articles could be used in recommendation for a wide variety of different users, who might take a liking to a specific article or a topic which is popular at that moment.
```
Så får vi også topic delen med, så er jeg rimelig tilfreds.

2021-04-20 11:23 UTC, Starrock45 approved these changes
Har kommenteret en suggested change. Vi må lige kigge på slutningen af afsnittet igen senere, når vi har nogle mere konkrete bud (muligvis fra vores diskussionsafsnit) på hvad metadataen kan give.

2021-04-21 07:13 UTC, MrLongbottom approved these changes

2021-04-21 08:45 UTC, merged