Pachinko generative process
MrLongbottom/P10-Article pull request #29
Opened 2021-04-22 09:11 UTC by slayeren

2021-04-22 09:25 UTC, MrLongbottom requested changes
overall godt, har lidt ændringer / små fejl

2021-04-22 09:25 UTC, MrLongbottom commented on sections/plate_notation.tex
> +More specifically, for each topic starting with the root topic $Z_{w1}$, we sample a topic from the next layer $Z_{w(l+1)}$ from that node's topic distribution $\theta_l^{(d)}$ based on observed data
```suggestion
More specifically, for each topic $Z_{wl}$ starting with the root topic $Z_{w1}$, we sample a topic from the next layer $Z_{w(l+1)}$ from that node's topic distribution $\theta_l^{(d)}$ based on observed data from that document.
```

2021-04-22 09:25 UTC, MrLongbottom commented on sections/plate_notation.tex
> +		\frac{n_{cw}^d + \beta_{w}}{n_{c} + \sum_{m} \beta_{m}}
```suggestion
		\frac{n_{1a}^d + \alpha_{1a}}{n_1^d + \sum_{a'} \alpha_{1a'}} \times
		\frac{n_{ab}^d + \alpha_{ab}}{n_a^d + \sum_{b'} \alpha_{ab'}}  \times 
		\frac{n_{bc}^d + \alpha_{bc}}{n_{b}^d + \sum_{c'} \alpha_{bc'}} \\ \times 
		\frac{n_{cw}^d + \beta_{w}}{n_{c} + \sum_{m} \beta_{m}} 
```
fjern gammel brug af 'r' og 'k' da de er blevet udskiftet med a,b,c

2021-04-22 09:25 UTC, MrLongbottom commented on sections/plate_notation.tex
> +As in \citet{li2006pachinko} $t_1$ is the root topic and $Z_{w2}$, $Z_{w3}$, $Z_{w4}$ are the three middle layers of topics in our 5-layer Pachinko model.
```suggestion
As in \citet{li2006pachinko} $t_1$ is the root topic and $Z_{w2}$, $Z_{w3}$, $Z_{w4}$ are topic assignments for the three middle layers of topics in our 5-layer Pachinko model.
```

2021-04-22 09:25 UTC, MrLongbottom commented on sections/plate_notation.tex
> +$Z_{-w}$ is the word topic assignment, for all other words than the one we are working on.
```suggestion
$Z_{-w}$ is the word topic assignment, for all other words except the one that is being updated.
```

2021-04-22 09:25 UTC, MrLongbottom commented on sections/plate_notation.tex
> +Without looking at the current object of iteration, $n_x^d$ is the number of times topic $tx$ occurs in document $d$.
```suggestion
Without looking at the current object of iteration, $n_x^d$ is the number of times topic $t_x$ occurs in document $d$. 
```

2021-04-22 09:25 UTC, MrLongbottom commented on sections/plate_notation.tex
> +The idea behind using five layers instead of four is because, the taxonomy field contains up to 5 layers of information.
```suggestion
\todo{describe why we use 5 layers.}
```
this is not true. its more complex than that. Vi bruger kun 2 lag fra taxonomy ikke 5.

2021-04-23 07:07 UTC, MrLongbottom approved these changes

2021-04-23 08:52 UTC, Starrock45 approved these changes

2021-04-23 08:52 UTC, Starrock45 commented on sections/plate_notation.tex
>  The plate notation for the \gls{pam} can be seen in \autoref{fig:pachinko}.
```suggestion
```
Kan nok bare fjernes, nu hvor figuren nævnes tidligere.

2021-04-23 11:36 UTC, merged