Added initial intro to appendix
MrLongbottom/P10-Article pull request #44
Opened 2021-05-06 09:21 UTC by slayeren

2021-05-06 09:23 UTC, slayeren commented on sections/appendix/Intro.tex
> +Within this appendix, we are expanding on many aspect of the aforementioned paper.
```suggestion
Within this appendix, we are expanding on many aspects of the aforementioned paper.

```

2021-05-10 08:31 UTC, Starrock45 requested changes
Mindre ting rundt omkring.

2021-05-10 08:31 UTC, Starrock45 commented on sections/appendix/Intro.tex
> +The paper, above, initialize and describe our problem and is results focused.
```suggestion
The paper above initializes and describes our problem and is results focused.
```

2021-05-10 08:31 UTC, Starrock45 commented on sections/appendix/Intro.tex
> +These extensions include:
```suggestion
This includes:
```

2021-05-10 08:31 UTC, Starrock45 commented on sections/appendix/Intro.tex
> +		\item An brief explanation of the process of training and evaluating our models.
```suggestion
		\item A brief explanation of the process of training and evaluating our models.
```

2021-05-10 08:31 UTC, Starrock45 commented on sections/appendix/Intro.tex
> +		\item The pseudo code for the Gibbs Sampler is explained and the extensions are described how they differ from the standard Gibbs Sampler.
```suggestion
		\item The code for the Gibbs sampler is explained and the other models we explored are described in how they differ from the standard Gibbs Sampler. 
```

2021-05-10 08:31 UTC, Starrock45 commented on sections/appendix/Intro.tex
> +		\item We explain the purpose and mathematical idea behind the three evaluation metrics, we use in the paper.
```suggestion
		\item We explain the purpose and mathematical ideas behind the three evaluation metrics we use in the paper.
```

2021-05-10 08:31 UTC, Starrock45 commented on sections/appendix/Intro.tex
> +		\item The specific modifications, we have implemented into our models, are evaluated and explain in detail.
```suggestion
		\item The specific modifications we have implemented into our models are evaluated and explain in detail.
```

2021-05-10 08:31 UTC, Starrock45 commented on sections/appendix/Intro.tex
> +	\item Tables
```suggestion
	\item Metadata
```

2021-05-10 08:31 UTC, Starrock45 commented on sections/appendix/Intro.tex
> +		\item The metadata is shown in data tables, specifically Author and Category.
```suggestion
		\item The metadata is shown in tables, specifically for the author and category metadata, and observations about the metadata labels are described.
```
Dog er der stadig mulighed for at tilføje et udsnit at taxonomy dataen i en tabel.

2021-05-10 08:31 UTC, Starrock45 commented on sections/appendix/Intro.tex
> +		\item We explore the application possibilities of our project, and propose various applications, which could be implemented at Nordjyske.
```suggestion
		\item We explore the application possibilities of our project and propose various applications which could be implemented at Nordjyske.
```

2021-05-10 08:31 UTC, Starrock45 commented on sections/appendix/Intro.tex
> +	\item Modifications
Jeg tænker at modifications skal være før metrics, men vi får at se hvad giver mest mening.

2021-05-10 08:37 UTC, MrLongbottom approved these changes

2021-05-10 08:37 UTC, MrLongbottom commented on sections/appendix/Intro.tex
> +The paper, above, initialize and describe our problem and is results focused.
```suggestion
In the main paper, we initialize and describe our problem with focus on results.
```

2021-05-10 12:06 UTC, Starrock45 commented on sections/appendix/Intro.tex
> +The paper, above, initialize and describe our problem and is results focused.
```suggestion
In the main paper, we initialize and describe our problem with a focus on results.
```

2021-05-10 12:07 UTC, Starrock45 approved these changes

2021-05-11 07:55 UTC, merged