Appendix pachinko results
MrLongbottom/P10-Article pull request #45
Opened 2021-05-07 08:35 UTC by MrLongbottom

2021-05-07 09:10 UTC, slayeren requested changes
kun stavefejl tror jeg :D

2021-05-07 09:10 UTC, slayeren commented on sections/appendix/pachinko_results.tex
> +Note that while most of the topics are semantically coherent, there are a some topics (eg. topic 19 and 42) which consist entirely of words which provide little context or semantic meaning.
```suggestion
Note that while most of the topics are semantically coherent, there are some topics (eg. topic 19 and 42) which consist entirely of words which provide little context or semantic meaning.
```

2021-05-07 09:10 UTC, slayeren commented on sections/appendix/pachinko_results.tex
> +The model has also learned to group words that do not belong into any good topics.
```suggestion
The model has also learned to group words that do not belong to any good topics.
```

2021-05-07 09:10 UTC, slayeren commented on sections/appendix/pachinko_results.tex
> +This is a good feature which allows the model to apply an extra layer of preprocessing, automatically filtering away irrellevant words into topics.
```suggestion
This is a good feature that allows the model to apply an extra layer of preprocessing, automatically filtering away irrelevant words into topics.
```

2021-05-07 09:10 UTC, slayeren commented on sections/appendix/pachinko_results.tex
> +However not all the connections make as much sense as these. For example the 'Kriminalitet' (Crime) topic has two filler topics: 42 and 75, one topic about economy: 60, one topic about politics: 8, a
```suggestion
However not all the connections make as much sense as these. 
For example, the 'Kriminalitet' (Crime) topic has two filler topics: 42 and 75, one topic about economy: 60, one topic about politics: 8, and one topic about sports: 86.
```

2021-05-10 07:32 UTC, MrLongbottom commented on sections/appendix/pachinko_results.tex
> +This is a good feature which allows the model to apply an extra layer of preprocessing, automatically filtering away irrellevant words into topics.
```suggestion
This is a good feature which allows the model to apply an extra layer of preprocessing, automatically filtering away irrellevant words into topics.
\todo[inline]{ref to hlda and possibly one newer paper (simba knew one) that does the same thing.}
```

2021-05-10 07:32 UTC, MrLongbottom commented on sections/appendix/pachinko_results.tex
> +This is a good feature that allows the model to apply an extra layer of preprocessing, automatically filtering away irrelevant words into topics.
```suggestion
This is a good feature that allows the model to apply an extra layer of preprocessing, automatically filtering away irrelevant words into topics.
\todo[inline]{ref to hlda and possibly one newer paper (simba knew one) that does the same thing.}
```

2021-05-10 08:38 UTC, slayeren approved these changes

2021-05-10 09:21 UTC, Starrock45 requested changes

2021-05-10 09:21 UTC, Starrock45 commented on sections/appendix/pachinko_results.tex
> +\todo[inline]{ref to hlda and possibly one newer paper (simba knew one) that does the same thing.}
```suggestion
\todo[inline]{ref to hlda and "Topic Modeling in Embedding Spaces" that does the same thing.}
```
Det kan ses i figur 6 i den artikel.

2021-05-10 09:21 UTC, Starrock45 commented on sections/appendix/pachinko_results.tex
> +Note that while most of the topics are semantically coherent, there are some topics (eg. topic 19 and 42) which consist entirely of words which provide little context or semantic meaning.
```suggestion
Note that while most of the topics are semantically coherent, there are some topics (e.g. topic 19 and 42) which consist entirely of words which provide little context or semantic meaning.
```

2021-05-10 09:21 UTC, Starrock45 commented on sections/appendix/pachinko_results.tex
> +		\caption{Top 10 words for each lowest level topic in the results of the pachinko model \label{tab:pachinko_topics}}\\
```suggestion
		\caption{Top 10 words for each lowest level topic in the results of the pachinko model. \label{tab:pachinko_topics}}\\
```

2021-05-10 09:21 UTC, Starrock45 commented on sections/appendix/pachinko_results.tex
> +	\caption{Ids of the top 5 most occuring fourth layer topics for each third layer topic from the pachinko model. See table \autoref{tab:pachinko_topics} for most occouring words for each id.}
```suggestion
	\caption{IDs of the top 5 most occurring fourth layer topics for each third layer topic from the pachinko model. See \autoref{tab:pachinko_topics} for the most occurring words for each ID.}
```

2021-05-10 09:21 UTC, Starrock45 commented on sections/appendix/pachinko_results.tex
> +		Taxonomy Name & Top 5 Topic ids & Taxonomy Name & Top 5 Topic ids & Taxonomy Name & Top 5 Topic ids \\ \hline
```suggestion
		Taxonomy Name & Top 5 Topic IDs & Taxonomy Name & Top 5 Topic IDs & Taxonomy Name & Top 5 Topic IDs \\ \hline
```

2021-05-12 12:14 UTC, Starrock45 approved these changes

2021-05-13 07:21 UTC, merged