Category-topic model analysis
MrLongbottom/P10-Article pull request #49
Opened 2021-05-11 11:04 UTC by Starrock45

2021-05-11 11:30 UTC, slayeren requested changes
enkelte rettelser

2021-05-11 11:30 UTC, slayeren commented on sections/discussion/category-topic.tex
> +Just at for the author-topic model, the similarity between pairs of categories can be calculated.
```suggestion
Just as for the author-topic model, the similarity between pairs of categories can be calculated.
```

2021-05-11 11:30 UTC, slayeren commented on sections/discussion/category-topic.tex
> +It is also clear that some of the topics, the model have learned, fit well with how some categories are used in the dataset.
```suggestion
It is also clear that some of the topics, the model has learned, fit well with how some categories are used in the dataset.
```

2021-05-12 12:20 UTC, MrLongbottom approved these changes

2021-05-12 12:20 UTC, MrLongbottom commented on sections/discussion/category-topic.tex
> +It is also clear that some of the topics, the model have learned, fit well with how some categories are used in the dataset.
```suggestion
It is also clear that some of the topics that the model have learned, fit well with how some categories are used in the dataset.
```

2021-05-12 12:47 UTC, Starrock45 commented on sections/discussion/category-topic.tex
> +It is also clear that some of the topics, the model have learned, fit well with how some categories are used in the dataset.
```suggestion
It is also clear that some of the topics that the model has learned, fit well with how some categories are used in the dataset.
```

2021-05-12 14:43 UTC, slayeren approved these changes

2021-05-13 07:25 UTC, merged