Pachinko Opdatering
MrLongbottom/P10-Article pull request #52
Opened 2021-05-12 09:21 UTC by MrLongbottom

Har prøvet at lave pachinko afsnittet en del mere forståligt.

2021-05-12 11:03 UTC, slayeren requested changes
Har nogle sætningsrettelser og lidt stave sager

2021-05-12 11:03 UTC, rasmus-e-christensen commented on sections/Dataset.tex
> +This field is only partially observed within the dataset, which means that ${\sim}25\%$ of the articles containing this field.
```suggestion
This field is only partially observed within the dataset, which means that ${\sim}25\%$ of the articles contain this field.
```

2021-05-12 11:03 UTC, rasmus-e-christensen commented on sections/plate_notation.tex
> +Pachinko allocation generalizes \gls{lda}, to be able to construct topic hiearchies based on any \gls{dag} structure.
```suggestion
Pachinko allocation generalizes the \gls{lda}, by constructing topic hierarchies based on any \gls{dag} structure.
```

2021-05-12 11:03 UTC, rasmus-e-christensen commented on sections/plate_notation.tex
> +\gls{pam} is a topic model focusing on finding topics of different abstraction level and modelling the connections between these topics.
```suggestion
\gls{pam} is a topic model focusing on finding topics of different abstraction levels and modeling the connections between these topics. 
```

2021-05-12 11:03 UTC, rasmus-e-christensen commented on sections/plate_notation.tex
> +Each node in the \gls{dag} structure represents a topic in the pachinko allocation model. However, unlike \gls{lda} where topics are distributions over words, in \gls{pam} topics are multinomial dist
```suggestion
Each node in the \gls{dag} structure represents a topic in the pachinko allocation model. 
However, unlike \gls{lda} where topics are distributions over words, in \gls{pam} topics are multinomial distributions over words and/or other topics further down the hierarchy of the  \gls{dag} structure.
```

2021-05-12 11:03 UTC, rasmus-e-christensen commented on sections/plate_notation.tex
> +In this paper we use a layered \gls{pam}, meaning that the \gls{dag} structure is divided into layers with every node in each layer having an edge going to every node in the next layer further down t
```suggestion
In this paper, we use a layered \gls{pam}, meaning that the \gls{dag} structure is divided into layers with every node in each layer is fully connected to every node in the next layer with the hierarchy.
```

2021-05-12 11:03 UTC, rasmus-e-christensen commented on sections/plate_notation.tex
> +We replicate some layers of the structure from our taxonomy dataset in our \gls{dag} structure, having some nodes represent a topic based on this specific taxonomy.
```suggestion
We replicate some layers, based on the structure from the taxonomy field within our dataset, in our \gls{dag} structure having some nodes represent a topic based on this specific taxonomy.
```

2021-05-12 11:03 UTC, rasmus-e-christensen commented on sections/plate_notation.tex
> +To make the algorithm construct the topics to be based on our taxonomies we will be introducing a novel locking mechanism to the gibbs sampler that will be used to run \gls{pam}.
```suggestion
To make the algorithm construct the topics to be based on our taxonomies, we introduce a novel locking mechanism for the Gibbs sampler that is being used to run \gls{pam}.
```

2021-05-12 11:03 UTC, rasmus-e-christensen commented on sections/plate_notation.tex
> +The first layer is the root layer, which all words are a part of.
```suggestion
The first layer is the root layer.
```

2021-05-12 11:03 UTC, rasmus-e-christensen commented on sections/plate_notation.tex
> +The second and third layers will be constructed based on the entries of first two positions in our taxonomy dataset, meaning there will be one node for each unique sub-taxonomy entry that is in the f
```suggestion
The second and third layers will be constructed based on the entries of the first two positions in our taxonomy metadata, meaning there will be one node for each unique sub-taxonomy entry that is in the first or second position in the taxonomy sequence.
For example "STEDER", which is taken from "STEDER/Danmark/Aalborg.
```

2021-05-12 11:03 UTC, rasmus-e-christensen commented on sections/plate_notation.tex
> +We only use the first two layers for this, as the these are among the most informative, and because introducing even more layers would slow down the training exponentially, as the probability of all
```suggestion
We only use the first two layers for this, as these are among the most informative, and because introducing even more layers would slow down the training exponentially, since the probability of all possible combinations of topics needs to be sampled for every word during training.
```

2021-05-12 11:03 UTC, rasmus-e-christensen commented on sections/plate_notation.tex
> +The fourth layer consists of $K = 90$ 'blank' topics, as with the other models we present in this paper.
```suggestion
The fourth layer consists of $K = 90$ 'blank' topics, as with the other models, we present in this paper.
```

2021-05-12 11:03 UTC, rasmus-e-christensen commented on sections/plate_notation.tex
> +This layer is added so that the model can construct its own topics based on the higher-level topics learned from our taxonomy data.
```suggestion
This layer is added so that the model can construct its own topics based on the higher-level topics learned from our taxonomy metadata.
```

2021-05-12 11:03 UTC, slayeren commented on sections/plate_notation.tex
> +First the multinomial distributions for each node in the \gls{dag} are sampled from dirichlet distributions based on $\alpha$ values.
```suggestion
First, the multinomial distributions for each node in the \gls{dag} are sampled from Dirichlet distributions based on $\alpha$ values.
```

2021-05-12 11:03 UTC, slayeren commented on sections/plate_notation.tex
> +Similarly for the second to last layer, the multinomial distribution over words are sampled from a dirichlet distribution based on a single $\beta$ value.
```suggestion
Similarly, for the second to last layer, the multinomial distribution over words is sampled from a Dirichlet distribution based on a single $\beta$ value.
```

2021-05-12 11:03 UTC, slayeren commented on sections/plate_notation.tex
> +For each word, a chain of topics is sampled by calculating the probability of all combination of topics and making a weighted sample.
```suggestion
For each word, a chain of topics is sampled by calculating the probability of all combinations of topics and making a weighted sample.
```

2021-05-12 11:03 UTC, slayeren commented on sections/plate_notation.tex
> +The root topic is not part of this equation since all words are part of it, so the probibility does not need to be calculated.
```suggestion
The root topic is not part of this equation since all words are part of it, so the probability does not need to be calculated.
```

2021-05-12 11:03 UTC, slayeren commented on sections/plate_notation.tex
> +However, for our dataset only $25\%$ of the documents have an observed taxonomy.
```suggestion
However, for our dataset, only $25\%$ of the documents have an observed taxonomy.
```

2021-05-12 12:01 UTC, MrLongbottom commented on sections/plate_notation.tex
> +Pachinko allocation generalizes \gls{lda}, to be able to construct topic hiearchies based on any \gls{dag} structure.
```suggestion
Pachinko allocation generalizes \gls{lda}, making it possible to construct topic hierarchies based on any \gls{dag} structure.
```

2021-05-12 12:01 UTC, MrLongbottom commented on sections/plate_notation.tex
> +In this paper we use a layered \gls{pam}, meaning that the \gls{dag} structure is divided into layers with every node in each layer having an edge going to every node in the next layer further down t
```suggestion
In this paper, we use a layered \gls{pam} meaning that the \gls{dag} structure is divided into layers with every node in each layer fully connected to every node in the next layer of the hierarchy.
```
```suggestion
In this paper we use a layered \gls{pam}, meaning that the \gls{dag} structure is divided into layers with every node in each layer fully connected to every node in the next layer of the hierarchy.
```
ville mene kun et af disse to kommaer skal være der.

2021-05-12 12:01 UTC, MrLongbottom commented on sections/plate_notation.tex
> +We replicate some layers of the structure from our taxonomy dataset in our \gls{dag} structure, having some nodes represent a topic based on this specific taxonomy.
```suggestion
We replicate some layers in our \gls{dag} structure based on the structure from the taxonomy field within our dataset, having some nodes represent a topic based on a specific taxonomy.
```

2021-05-12 12:01 UTC, MrLongbottom commented on sections/plate_notation.tex
> +To make the algorithm construct the topics to be based on our taxonomies we will be introducing a novel locking mechanism to the gibbs sampler that will be used to run \gls{pam}.
```suggestion
To make the algorithm construct the topics to be based on our taxonomies, we introduce a novel locking mechanism for the Gibbs sampler which we use to run \gls{pam}.
```

2021-05-12 12:01 UTC, MrLongbottom commented on sections/plate_notation.tex
> +The second and third layers will be constructed based on the entries of first two positions in our taxonomy dataset, meaning there will be one node for each unique sub-taxonomy entry that is in the f
```suggestion
The second and third layers will be constructed based on the entries of the first two positions in our taxonomy metadata, meaning there will be one node for each unique sub-taxonomy entry that is in the first or second position in the taxonomy sequence (e.g. "STEDER" and "Danmark", which is taken from "STEDER/Danmark/Aalborg", but not "Aalborg" since it is in the third position).
```

2021-05-12 12:04 UTC, MrLongbottom commented on sections/plate_notation.tex
> +However, for our dataset only $25\%$ of the documents have an observed taxonomy.
```suggestion
However, only $25\%$ of the documents have an observed taxonomy in our dataset.
```

2021-05-13 08:57 UTC, Starrock45 requested changes

2021-05-13 08:57 UTC, Starrock45 commented on sections/Dataset.tex
> +It is also possible for articles to contain multiple taxonomies sequences.
```suggestion
It is also possible for articles to contain multiple taxonomy sequences.
```

2021-05-13 08:57 UTC, Starrock45 commented on sections/plate_notation.tex
> +In order to handle the hierarchical structure of the taxonomy metadata field, we use a hierarchical topic model, namely the \acrlong{pam} from \citet{li2006pachinko}.
```suggestion
In order to handle the hierarchical structure of the taxonomy metadata field, we use a hierarchical topic model, namely the \acrfull{pam} from \citet{li2006pachinko}.
```

2021-05-13 08:57 UTC, Starrock45 commented on sections/plate_notation.tex
> +However, unlike \gls{lda} where topics are distributions over words, in \gls{pam} topics are multinomial distributions over words and/or other topics further down the hierarchy of the  \gls{dag} stru
```suggestion
However, unlike \gls{lda} where topics are distributions over words, in \gls{pam} topics are multinomial distributions over words and/or other topics further down the hierarchy of the \gls{dag} structure.
```

2021-05-13 08:57 UTC, Starrock45 commented on sections/plate_notation.tex
> +An example of the dag structure used in this paper is shown in \autoref{fig:pachinko_dag}.
```suggestion
An example of the \gls{dag} structure used in this paper is shown in \autoref{fig:pachinko_dag}.
```

2021-05-13 08:57 UTC, Starrock45 commented on sections/plate_notation.tex
> +In this paper we use a layered \gls{pam}, meaning that the \gls{dag} structure is divided into layers with every node in each layer having an edge going to every node in the next layer further down t
```suggestion
In this paper, we use a layered \gls{pam} meaning that the \gls{dag} structure is divided into layers, with every node in each layer fully connected to every node in the next layer of the hierarchy.
```

2021-05-13 08:57 UTC, Starrock45 commented on sections/plate_notation.tex
> +The first layer consists of only the root node, a topic which all documents are part of, and the bottom layer consisting of leaf nodes, which are the only nodes to contain distributions over words, a
```suggestion
The first layer consists of only the root node, a topic which all documents are part of, and the bottom layer consists of leaf nodes, which are the only nodes to contain distributions over words, and they have no other topics in their distribution.
```

2021-05-13 08:57 UTC, Starrock45 commented on sections/plate_notation.tex
> +We use a five-level pachinko tree structure, following the format presented by \cite{li2006pachinko}.
```suggestion
We use a five-level pachinko tree structure, following the format presented by \citet{li2006pachinko}.
```

2021-05-13 08:57 UTC, Starrock45 commented on sections/plate_notation.tex
> +The second and third layers will be constructed based on the entries of first two positions in our taxonomy dataset, meaning there will be one node for each unique sub-taxonomy entry that is in the f
@MrLongbottom's sætning bliver måske lidt for lang, men kan godt lide de ekstra detaljer.

2021-05-13 08:57 UTC, Starrock45 commented on sections/plate_notation.tex
> +The generative process for PAM is described as follows:
```suggestion
The generative process for \gls{pam} is described as follows:
```

2021-05-13 08:57 UTC, Starrock45 commented on sections/plate_notation.tex
> +While it is possible to use different $\alpha$ values for each layer, we found through experimentation using the same $\alpha$ value for all layers still provided good results.
```suggestion
While it is possible to use different $\alpha$ values for each layer, we found through experimentation that using the same $\alpha$ value for all layers still provided good results.
```

2021-05-13 08:57 UTC, Starrock45 commented on sections/plate_notation.tex
> +After all topic distribution have been sampled, documents are created by sampling words in the following manner:
```suggestion
After all topic distributions have been sampled, documents are created by sampling words in the following manner:
```

2021-05-13 08:57 UTC, Starrock45 commented on sections/plate_notation.tex
> +As in \citet{li2006pachinko} $Z_{w2}$, $Z_{w3}$, $Z_{w4}$ are topic assignments for the three middle layers of topics in our 5-layer Pachinko model.
```suggestion
As in \citet{li2006pachinko}, $Z_{w2}$, $Z_{w3}$, $Z_{w4}$ are topic assignments for the three middle layers of topics in our 5-layer Pachinko model.
```

2021-05-13 08:57 UTC, Starrock45 commented on sections/plate_notation.tex
> +$n_x$ is the number of times topic $t_x$ occurs in the corpus according to $Z_{-w}$ and $n_{xw}$ is the number of times a word $w$ is in $t_x$ according to $Z_{-w}$.
```suggestion
$n_x$ is the number of times topic $t_x$ occurs in the corpus according to $Z_{-w}$, and $n_{xw}$ is the number of times a word $w$ is in $t_x$ according to $Z_{-w}$.
```

2021-05-13 08:57 UTC, Starrock45 commented on sections/plate_notation.tex
> +However, for our dataset only $25\%$ of the documents have an observed taxonomy.
```suggestion
However, only $25\%$ of the documents in our dataset have an observed taxonomy.
```

2021-05-14 07:11 UTC, Starrock45 approved these changes

2021-05-14 07:11 UTC, slayeren approved these changes

2021-05-14 07:12 UTC, merged