Vejleder comments
MrLongbottom/P10-Article pull request #53
Opened 2021-05-12 09:47 UTC by slayeren

2021-05-13 09:25 UTC, Starrock45 requested changes

2021-05-13 09:25 UTC, Starrock45 commented on sections/plate_notation.tex
> +We have created a combination model to see whether using multiple meta-data fields at the same time to draw topics, would have an effect on the performance of the topic model.
```suggestion
We have created a combination model to see whether using multiple metadata fields at the same time to draw topics, would affect the performance of the topic model.
```

2021-05-13 09:25 UTC, Starrock45 commented on sections/plate_notation.tex
> +The first model, we have created is the Author-Category combination model.
```suggestion
The first model we have created is the Author-Category combination model.
```

2021-05-13 09:25 UTC, Starrock45 commented on sections/plate_notation.tex
> +Then, when sampling for a new word topic, we normalize the product of the multiplication to sum to 1, which also makes it a distribution. \vejleder[inline]{mathify this}
```suggestion
To combine the Author and Category metadata, we multiply the topic distributions $\theta_a$ and $\theta_c$ when sampling a new word topic.
Though, before sampling the word topic, we normalize the product of the multiplication to sum to 1, which also makes it a distribution. \vejleder[inline]{mathify this}
```

2021-05-13 09:25 UTC, Starrock45 commented on sections/related_works.tex
> +SLDA learns a model given the restriction of only having one label per document, while LLDA allows multiple labels per document, though it requires the number of topics to be the same as the number o
```suggestion
SLDA learns a model given the restriction of only having one label per document, while LLDA allows multiple labels per document, though it requires the number of topics to be the same as the number of unique metadata labels.
```

2021-05-13 09:54 UTC, Starrock45 approved these changes

2021-05-14 06:53 UTC, MrLongbottom approved these changes

2021-05-14 07:16 UTC, merged