Appendix metadata labels section restructure
MrLongbottom/P10-Article pull request #54
Opened 2021-05-12 11:49 UTC by Starrock45

Omstruktureret metadata labels afsnittet så der er tydeligere sammenhæng. Tilføjede også taxonomy tabellen med counts af dokumenter og beskrev nogle observationer ud fra dette. Der er også rettet/tilføjet små ting rundt omkring.

2021-05-12 12:15 UTC, slayeren requested changes

2021-05-12 12:15 UTC, slayeren commented on sections/appendix/taxonomies.tex
> +It is worth mentioning that, while the counts of the labels are directly linked the amount of documents in the whole dataset, they are also connected to the size of the previous layer's taxonomy.
```suggestion
It is worth mentioning that, while the counts of the labels are directly linked to the number of documents in the whole dataset, they are also connected to the size of the previous layer's taxonomy.
```

2021-05-12 12:15 UTC, slayeren commented on sections/appendix/taxonomies.tex
> +This gives an indication that the subject taxonomies in general are much smaller in size.
```suggestion
This indicates that the subject taxonomies, in general, are much smaller in size.
```

2021-05-12 14:44 UTC, slayeren approved these changes

2021-05-14 06:54 UTC, MrLongbottom approved these changes

2021-05-14 07:08 UTC, merged