Appendix/cat auth pachinko
MrLongbottom/P10-Article pull request #64
Opened 2021-05-18 09:05 UTC by MrLongbottom

Der kommer en opdatering til denne PR senere når jeg har fået kørt en normal pachinko.

2021-05-18 09:10 UTC, slayeren requested changes
ser fint ud men har et par ting :)

2021-05-18 09:10 UTC, slayeren commented on sections/appendix/cat_auth_pachinko.tex
> +Given the good results of the taxonomy \gls{pam}, we decided to also test \gls{pam} with the two other metadata fields: author and category.
```suggestion
Given the good results of the taxonomy \gls{pam}, we decided to test \gls{pam} with the two other metadata fields: Author and Category.
```

2021-05-18 09:10 UTC, slayeren commented on sections/appendix/cat_auth_pachinko.tex
> +Instead a four-layer \gls{pam} will be used, with a root layer, a metadata layer where words are locked into topics using the technique outlined in \autoref{sec:appendix/locking}, a layer with 90 'bl
```suggestion
Instead, a four-layer \gls{pam} will be used, with a root layer, a metadata layer where words are locked into topics using the technique outlined in \autoref{sec:appendix/locking}, a layer with 90 'blank' topics, and a word layer.
```

2021-05-18 09:10 UTC, slayeren commented on sections/appendix/cat_auth_pachinko.tex
> +As can be seen from the results in \autoref{tab:cat_auth_pachinko_results}, these models achieve greater results than the previous author and category models and \gls{lda} model.
```suggestion
As can be seen from the results in \autoref{tab:cat_auth_pachinko_results}, these models achieve greater results than the previous Author and Category models and \gls{lda} model.
```

2021-05-18 09:10 UTC, slayeren commented on sections/appendix/cat_auth_pachinko.tex
> +However the taxonomy \gls{pam} does do better.
```suggestion
However, the taxonomy \gls{pam} is still better overall.
```

2021-05-18 09:10 UTC, slayeren commented on sections/appendix/cat_auth_pachinko.tex
> +The same conlusion is reached after manual inspection of the topics of these models.
```suggestion
The same conclusion is reached after manual inspection of the topics of these models.
```
hvad? hvilken conclusion? beskriv hvad vi concludere

2021-05-18 12:19 UTC, Starrock45 approved these changes

2021-05-18 12:19 UTC, Starrock45 commented on sections/appendix/cat_auth_pachinko.tex
> +As can be seen from the results in \autoref{tab:cat_auth_pachinko_results}, these models achieve greater results than the previous author and category models and \gls{lda} model.
```suggestion
As can be seen from the results in \autoref{tab:cat_auth_pachinko_results}, these models achieve better results than the previous author and category models and the \gls{lda} model.
```

2021-05-18 12:19 UTC, Starrock45 commented on sections/appendix/cat_auth_pachinko.tex
> +	\begin{tabular}{l|c|c|c}
```suggestion
	\begin{tabular}{l|c}
```

2021-05-18 12:26 UTC, Starrock45 commented on sections/appendix/cat_auth_pachinko.tex
> +		\textbf{Category \acrlong{pam}} & \textbf{0.585} \\
Jeg ville nok også rykke dem rundt så rækkefølgen passer med vores anden resultattabel.

2021-05-19 12:55 UTC, Starrock45 commented on sections/appendix/cat_auth_pachinko.tex
> +		\textbf{Category \acrlong{pam}} & \textbf{0.585} \\
```suggestion
		\acrfull{lda} model & 0.520 \\
		Author-Topic \acrlong{lda} model & 0.335 \\
		Category-Topic \acrlong{lda} model & 0.370 \\
		Taxonomy \acrlong{pam} & 0.660 \\
		\textbf{Author \acrlong{pam}} & \textbf{0.598} \\
		\textbf{Category \acrlong{pam}} & \textbf{0.585} \\
```
Det var vidst det her jeg tænkte.

2021-05-20 08:47 UTC, slayeren approved these changes

2021-05-21 06:53 UTC, merged