pachinko generative process
MrLongbottom/P10-Article pull request #69
Opened 2021-05-19 12:32 UTC by MrLongbottom

almost word for word repetition of the pachinko paper, but i reference them so it should be fine.

2021-05-19 13:18 UTC, Starrock45 requested changes

2021-05-19 13:18 UTC, Starrock45 commented on sections/plate_notation.tex
> +		\item Sample a topic path $\mathbf{z}_w$ of length $L_w: < z_{w1}, z_{w2}, \dots, z_{wL_w} >$. $z_{w1}$ is always the root and $z_{w1}$ through $z_{wL_w}$ are topic nodes in $T$. $z_{wi}$ is a chil
```suggestion
		\item Sample a topic path $\mathbf{z}_w$ of length $L_w: < z_{w1}, z_{w2}, \dots, z_{wL_w} >$. $z_{w1}$ is always the root and $z_{w1}$ through $z_{wL_w}$ are topic nodes in $T$. $z_{wi}$ is a child of $z_{w(i-1)}$ and it is sampled according to the multinomial distribution $\theta_{z_{wL_w}}^{(d)}$.
```

2021-05-19 13:18 UTC, Starrock45 commented on sections/plate_notation.tex
> +$T = {t_1, t_2, \dots, t_s}$ os the set of topics in the \gls{pam}.
```suggestion
$T = {t_1, t_2, \dots, t_s}$ is the set of topics in the \gls{pam}. 
```

2021-05-19 13:18 UTC, Starrock45 commented on sections/plate_notation.tex
> +$g_i(\alpha_i)$ is a Dirichlet distribution based on a vector $\alpha_i$ which has the same dimention as the number of children in $t_i$.
```suggestion
$g_i(\alpha_i)$ is a Dirichlet distribution based on a vector $\alpha_i$ which has the same dimension as the number of children in $t_i$.
```

2021-05-19 13:18 UTC, Starrock45 commented on sections/plate_notation.tex
> +Illustration of the plate notation for \gls{pam} can be found in \autoref{fig:pachinko}.
```suggestion
An illustration of the plate notation for \gls{pam} can be found in \autoref{fig:pachinko}.
```

2021-05-19 13:18 UTC, Starrock45 commented on sections/plate_notation.tex
> +While it is possible to use different $\alpha$ values for each topic as shown in here, we found through experimentation that using the same $\alpha$ value for all layers still provided good results.
```suggestion
While it is possible to use different $\alpha$ values for each topic, as shown here, we found through experimentation that using the same $\alpha$ value for all layers still provided good results.
```

2021-05-19 13:18 UTC, Starrock45 commented on sections/plate_notation.tex
> +		\item Sample word $w$ from $\theta_{z_{wL_w}}^{(d)}$.
Matematikken ser lidt mystisk ud i artiklen lige nu, med noget underlig spacing og overlap.

2021-05-19 13:18 UTC, Starrock45 commented on sections/plate_notation.tex
> +	\item Sample $\theta_{t_1}^{(d)}, \theta_{t_2}^{(d)}, \dots, \theta_{t_s}^{(d)}$ from $g_1(\alpha_1), g_2(\alpha_2), \dots, g_s(\alpha_s)$, where $\theta_{t_i}^{(d)}$ is a multinomial distribution o
Skriver vi nogen steder hvad g_1, g_2 osv. er? Kunne ikke lige finde det.

2021-05-20 08:06 UTC, slayeren approved these changes
enig med dennis

2021-05-20 12:37 UTC, Starrock45 commented on sections/plate_notation.tex
> +$T = {t_1, t_2, \dots, t_s}$ os the set of topics in the \gls{pam}.
```suggestion
$T = {t_1, t_2, \dots, t_s}$ is the set of topics in the \gls{pam}. 
```

2021-05-20 12:37 UTC, Starrock45 commented on sections/plate_notation.tex
> +		\item Sample a topic path $\mathbf{z}_w$ of length $L_w: < z_{w1}, z_{w2}, \dots, z_{wL_w} >$. $z_{w1}$ is always the root and $z_{w1}$ through $z_{wL_w}$ are topic nodes in $T$. $z_{wi}$ is a chil
Der er stadig et lille problem med L:, hvor kolon er for langt væk:
![image](https://user-images.githubusercontent.com/1732686/118979445-c4914180-b978-11eb-85ea-3d38c1555ee8.png)
I Pachinko artiklen:
![image](https://user-images.githubusercontent.com/1732686/118979525-d8d53e80-b978-11eb-838f-d5913fd39f39.png)

2021-05-20 12:40 UTC, Starrock45 commented on sections/plate_notation.tex
> +Each topic $t_i$ is associated with a Dirichlet distribution $g_i(\alpha_i)$ based on a vector $\alpha_i$ which has the same dimention as the number of children in $t_i$.
```suggestion
Each topic $t_i$ is associated with a Dirichlet distribution $g_i(\alpha_i)$ based on a vector $\alpha_i$ which has the same dimension as the number of children in $t_i$.
```

2021-05-21 07:29 UTC, Starrock45 approved these changes

2021-05-21 07:46 UTC, merged