fixed category in main paper
MrLongbottom/P10-Article pull request #72
Opened 2021-05-20 11:42 UTC by slayeren

2021-05-20 13:03 UTC, Starrock45 requested changes
Forslag

2021-05-20 13:03 UTC, Starrock45 commented on sections/Dataset.tex
> +Filtering away all categories covering less than $140$ documents (approximately $0.01\%$ of the total document set) and combining them into a single new 'misc' category of size $229$.
```suggestion
After filtering away all categories covering less than $140$ documents (approximately $0.01\%$ of the total document set) and combining them into a single new 'misc' category of size $229$, $34$ categories remain.
```

2021-05-20 13:03 UTC, Starrock45 commented on sections/Dataset.tex
> +The smallest category consist of $188$ documents, and for all categories, the median category size is $3022$.
```suggestion
The smallest category consists of $188$ documents, and for all categories, the median category size is $3022$.
```

2021-05-20 13:03 UTC, Starrock45 commented on sections/appendix/metadata_labels.tex
> +	\label{tab:statistics_over_metadata}
```suggestion
```
? Der er allerede en label 'tab:meta_prepro_stats'

2021-05-20 13:03 UTC, Starrock45 commented on sections/Dataset.tex
> +All of the category labels can be seen in \autoref{tab:category_table} in \autoref{sec:appendix_meta_data} and the statistics in \autoref{tab:statistics_over_metadata} in \autoref{sec:appendix_meta_d
```suggestion
All of the category labels can be seen in \autoref{tab:category_table} and the statistics in \autoref{tab:meta_prepro_stats}.
```
Afsnittet behøves nok ikke nævnes alligevel.

2021-05-20 13:03 UTC, Starrock45 commented on sections/Dataset.tex
>  The categories from the 3rd quartile and up do become much larger compared to the median, and there is an outlier with 20241 documents.
```suggestion
\autoref{fig:category_box} shows an overview of the size of the categories after filtering.
The categories from the 3rd quartile and up do become much larger compared to the median, and there is an outlier with 20241 documents.
```
Har bare tilføjet sætningen der blev slettet. Tænker det er ok at nævne at figuren findes, selvom at den er i appendix. Ellers skal figuren alligevel nævnes et andet sted.

2021-05-20 13:05 UTC, Starrock45 commented on sections/Dataset.tex
> -\end{figure}
Skulle den ikke bare i appendix?

2021-05-21 07:04 UTC, slayeren commented on sections/Dataset.tex
> -\end{figure}
Jeg ved ikke hvor jeg skulle ligge den henne

2021-05-21 07:15 UTC, MrLongbottom commented on sections/Dataset.tex
> -\end{figure}
jeg syntes godt vi kunne flytte det til appendix

2021-05-21 10:14 UTC, Starrock45 commented on sections/Dataset.tex
> -\end{figure}
Den kan nok godt bare smides et sted i category metadata afsnittet i appendix. Der er alligevel andre boxplot figurer der.

2021-05-21 10:15 UTC, Starrock45 approved these changes
Mangler bare de sidste kommentarer

2021-05-24 12:29 UTC, MrLongbottom commented on sections/Dataset.tex
> -\end{figure}
er dette blevet tilføjet til appendix?
@slayeren @Starrock45

2021-05-24 12:48 UTC, Starrock45 commented on sections/Dataset.tex
> -\end{figure}
Jeg kan godt lige prøve at tilføje den et sted.

2021-05-25 06:47 UTC, MrLongbottom approved these changes

2021-05-25 07:21 UTC, merged