Perplexity move
MrLongbottom/P10-Article pull request #73
Opened 2021-05-21 11:22 UTC by slayeren

2021-05-21 11:23 UTC, slayeren commented on sections/appendix/perplexity.tex
> +One of the evaluation metric, that is commonly used to evaluate topic models, is perplexity.
```suggestion
One evaluation metric, that is commonly used to evaluate topic models, is perplexity.

```

2021-05-21 13:36 UTC, MrLongbottom approved these changes

2021-05-24 08:06 UTC, Starrock45 approved these changes
Enkelt forslag til ændret sætning

2021-05-24 08:06 UTC, Starrock45 commented on sections/appendix/perplexity.tex
> +But because perplexity is not specific to topic models, and by itself does not give an indication of how coherent topics are, it is mainly used as a secondary evaluation~\cite{tea_leaves}.
```suggestion
Even though perplexity is not specific to topic models and by itself does not give an indication of how coherent topics are, we show the perplexity results for our models in \autoref{tab:_extra_metric_results}.
```

2021-05-24 08:14 UTC, Starrock45 commented on paper.tex
> +\input{sections/appendix/perplexity.tex}
```suggestion
%\input{sections/appendix/perplexity.tex}
```

2021-05-24 08:44 UTC, Starrock45 requested changes

2021-05-24 08:44 UTC, Starrock45 commented on sections/appendix/Overview.tex
> +The evaluation metrics chosen for the experiment are topic coherence and topic difference.
Det vil skabe konflikt med det nye overview på main.

2021-05-24 08:44 UTC, Starrock45 commented on sections/appendix/models.tex
> +In an attempt to improve these results, we combine the original \gls{lda} model with these models, adding a topic distribution for each document and combining it with the existing topics distribution
```suggestion
In an attempt to improve these results, we combine the original \gls{lda} model with these models, adding a topic distribution for each document and combining it with the existing topics distributions, as with the Author-Category model, which is explained in \autoref{sec:combination}.
```
Den hedder "sec:combination" på main

2021-05-24 08:44 UTC, Starrock45 commented on sections/appendix/models.tex
> +	\caption{Bolded results are the new models, which have been run.}
```suggestion
	\caption{Bolded results are the new models that have been run.}
```

2021-05-24 08:44 UTC, Starrock45 commented on sections/appendix/models.tex
> +		\textbf{Author-Doc Model} & \textbf{0.543} & \textbf{0.574} \\
```suggestion
		\textbf{Author-Category Model} & \textbf{0.390} & \textbf{0.537} \\
		\textbf{Author-Doc Model} & \textbf{0.543} & \textbf{0.574} \\
```
Author-category skulle ikke fjernes

2021-05-24 09:03 UTC, slayeren commented on sections/appendix/Overview.tex
> +The evaluation metrics chosen for the experiment are topic coherence and topic difference.
Så må vi lige kigge på overview igen :)

2021-05-24 09:13 UTC, Starrock45 commented on sections/appendix/Overview.tex
> +The evaluation metrics chosen for the experiment are topic coherence and topic difference.
? Overview er ændret på main til ikke at nævne perplexity, så der burde ikke skulle gøres noget.

2021-05-24 09:15 UTC, Starrock45 approved these changes

2021-05-24 09:15 UTC, Starrock45 commented on sections/appendix/Overview.tex
> +The evaluation and results are presented in \autoref{sec:experiment} and are analyzed and discussed in \autoref{sec:discussion}.
Jeg håber bare du har copy pasted fra main, selvom jeg ikke ved hvorfor.

2021-05-24 09:36 UTC, slayeren commented on sections/appendix/Overview.tex
> +The evaluation and results are presented in \autoref{sec:experiment} and are analyzed and discussed in \autoref{sec:discussion}.
jeg har bare taget det fra main

2021-05-24 11:01 UTC, MrLongbottom approved these changes

2021-05-24 11:13 UTC, merged