Application Appendix Rewrite
MrLongbottom/P10-Article pull request #89
Opened 2021-05-27 10:20 UTC by MrLongbottom

Removed most of the text i considered non-essential or focusing on something other than applications.
Also removed most of the ending about how metadata affects topics as we already do mention it in the article and the questions we ask are not answered anywhere so they might end up hurting us.
The new text is focused more on giving more examples of applications and making the examples a bit more concrete.

2021-05-27 10:20 UTC, MrLongbottom commented on sections/appendix/applications.tex
>  One very important problem, within news agencies, is recommendation of articles.
```suggestion
Another very important problem, within news agencies, is recommendation of articles.
```

2021-05-27 10:22 UTC, MrLongbottom commented on sections/appendix/applications.tex
> +A topic model might also be used to fill in missing information to the dataset.
```suggestion
A topic model might also be used to fill in missing meta information in a article dataset.

```

2021-05-27 11:01 UTC, slayeren requested changes
nogle enkelte stavefejl :) eller ser det fint ud

2021-05-27 11:01 UTC, rasmus-e-christensen commented on sections/appendix/applications.tex
> +News media groups, like Nordjyske, are trying to find new ways of integrating smarter and more intelligent methods for keeping their customers, and using topic modeling can help improve their process
```suggestion
News media groups, like Nordjyske, are trying to find new ways of integrating smarter and more intelligent methods for keeping their customers, and using topic modeling can help improve their processes such as searching, recommendation, the grouping of articles, information completion, etc.
```

2021-05-27 11:01 UTC, rasmus-e-christensen commented on sections/appendix/applications.tex
> +We will briefly give an overview of each of these to explain how topic modelling might play a role in improving these processes.
```suggestion
We will briefly give an overview of each of these to explain how topic modeling might play a role in improving these processes.
```

2021-05-27 11:01 UTC, rasmus-e-christensen commented on sections/appendix/applications.tex
> +These techniques can be particularly useful as they can help find articles that do not use any of the words in given query, but are still relevant to the query, which is a property that most basic se
```suggestion
These techniques can be particularly useful as they can help find articles that do not use any of the words in a given query but are still relevant to the query, which is a property that most basic search algorithms do not possess.
```

2021-05-27 11:01 UTC, rasmus-e-christensen commented on sections/appendix/applications.tex
> +Another very important problem, within news agencies, is recommendation of articles.
```suggestion
Another very important problem, within news agencies, is the recommendation of articles.
```

2021-05-27 11:01 UTC, rasmus-e-christensen commented on sections/appendix/applications.tex
> +Topic models can be used particularly for content-based filtering, finding other articles that have similar topics either to a users preferences based on their history or to another article.
```suggestion
Topic models can be used particularly for content-based filtering, finding other articles with similar topics either to users' preferences based on their history, or other similar articles.
```

2021-05-27 11:01 UTC, slayeren commented on sections/appendix/applications.tex
> +Grouping together items, or clustering, can serve many different purposes. Topic modelling provides a new way of grouping together articles based on topic similiarity.
```suggestion
Grouping together items, or clustering, can serve many different purposes. 
Topic modeling provides a new way of grouping together articles based on topic similarity.
```

2021-05-27 11:01 UTC, slayeren commented on sections/appendix/applications.tex
> +A topic model might also be used to fill in missing meta information in a article dataset.
```suggestion
A topic model might also be used to fill in missing meta information in an article dataset.
```

2021-05-27 12:46 UTC, Starrock45 approved these changes
Kun enkelte ting.

2021-05-27 12:46 UTC, Starrock45 commented on sections/appendix/applications.tex
> +This problem could be alleviated by using the topics created by our topic models, by performing query expansions finding similar words to the ones that appear in the query, providing more context to
```suggestion
This problem could be alleviated by using the topics created by our topic models for performing query expansions finding similar words to the ones that appear in the query, providing more context to find results from.
```

2021-05-27 12:46 UTC, Starrock45 commented on sections/appendix/applications.tex
> +Another very important problem, within news agencies, is recommendation of articles.
```suggestion
Another very important problem within news agencies is the recommendation of articles.
```

2021-05-27 12:46 UTC, Starrock45 commented on sections/appendix/applications.tex
> +For example with the taxonomy-topic model, we sample new taxonomies for the majority of the dataset which does not already have a taxonomy entry.
```suggestion
For example, with the taxonomy-topic model, we sample new taxonomies for the majority of the dataset, which does not already have a taxonomy entry.
```

2021-05-28 07:04 UTC, slayeren approved these changes

2021-05-28 07:15 UTC, merged