Mention main novelties at the end of the introduction
MrLongbottom/P10-Article pull request #91
Opened 2021-05-27 13:23 UTC by Starrock45

Burde forhåbentlig tydeliggøre hvad der er novel i vores artikel.

2021-05-27 13:28 UTC, rasmus-e-christensen approved these changes

2021-05-28 07:07 UTC, MrLongbottom requested changes
prøvede at tilføje at det at bruge pam til metadata også er en novelty i sig selv

2021-05-28 07:07 UTC, MrLongbottom commented on sections/introduction.tex
> +These categorical metadata are the basis for the novelties in this paper, which is our category-topic model that makes a topic distribution for each category in the dataset and a locking mechanism fo
```suggestion
These categorical metadata are the basis for the novelties in this paper, which is our category-topic model that makes a topic distribution for each category in the dataset and using \gls{pam} on a existing hierarchy (taxonomy metadata) by applying a locking mechanism.
```

2021-05-28 07:26 UTC, slayeren commented on sections/introduction.tex
> +These categorical metadata are the basis for the novelties in this paper, which is our category-topic model that makes a topic distribution for each category in the dataset and a locking mechanism fo
```suggestion
These categorical metadata are the basis for the novelties in this paper, which is our category-topic model that makes a topic distribution for each category in the dataset and using \gls{pam} on an existing metadata hierarchy (taxonomy) by applying a locking mechanism.
```

2021-05-28 07:29 UTC, MrLongbottom approved these changes

2021-05-28 07:29 UTC, merged